"""
KekuleExtension.py — GUI extension for Kekule bond-order optimization.

Provides UI panel for running the Kekule pi-bond-order optimizer on the current
molecule (from backend or generated by AsciiArtExtension). Supports two-phase
solve (delocalized + localized) with symmetry-breaking noise.

Wired through ExtensionManager as 'kekule' extension.
"""

from PyQt5 import QtWidgets, QtCore
import numpy as np

from .ExtensionManager import UIComponents
from spammm.GUI.LayoutPolicy import apply_tight, SPACING, ROW_SPACING, make_flow, BUTTON_MAX_WIDTH, SPIN_MAX_WIDTH, COMBO_MAX_WIDTH, GridPlacer
from spammm.topology.KekulePure import run_kekule_solver, localize_kekule, make_n_pi


def build_ui(window):
    """Build Kekule heterocycle panel for the SPAMMM GUI.

    Returns ExtensionManager.UIComponents.
    """
    panel = QtWidgets.QWidget()
    layout = QtWidgets.QVBoxLayout(panel)
    apply_tight(layout)

    # --- Row 4: Kekule solver parameters ---
    g4 = GridPlacer(cols=6)
    window.kek_kval_spin = QtWidgets.QDoubleSpinBox()
    window.kek_kval_spin.setRange(0.1, 1000.0)
    window.kek_kval_spin.setValue(50.0)
    window.kek_kval_spin.setMaximumWidth(SPIN_MAX_WIDTH)
    g4.add_pair("Kval:", window.kek_kval_spin, label_span=1, input_span=2)
    window.kek_kloc_spin = QtWidgets.QDoubleSpinBox()
    window.kek_kloc_spin.setRange(0.0, 100.0)
    window.kek_kloc_spin.setValue(5.0)
    window.kek_kloc_spin.setMaximumWidth(SPIN_MAX_WIDTH)
    g4.add_pair("Kloc:", window.kek_kloc_spin, label_span=1, input_span=2)
    window.kek_karo_spin = QtWidgets.QDoubleSpinBox()
    window.kek_karo_spin.setRange(0.0, 10.0)
    window.kek_karo_spin.setSingleStep(0.1)
    window.kek_karo_spin.setValue(0.5)
    window.kek_karo_spin.setMaximumWidth(SPIN_MAX_WIDTH)
    g4.add_pair("Karo:", window.kek_karo_spin, label_span=1, input_span=2)
    layout.addLayout(g4.layout())

    # --- Row 5: Aromatic + Solve ---
    g5 = GridPlacer(cols=6)
    window.kek_aromatic_chk = QtWidgets.QCheckBox("Aromatic")
    window.kek_aromatic_chk.setChecked(True)
    g5.add(window.kek_aromatic_chk, span=2)
    window.kek_solve_btn = QtWidgets.QPushButton("Solve")
    window.kek_solve_btn.clicked.connect(lambda: _on_solve(window))
    g5.add(window.kek_solve_btn, span=2)
    window.kek_solve_current_btn = QtWidgets.QPushButton("Solve Current")
    window.kek_solve_current_btn.clicked.connect(lambda: _on_solve_current(window))
    g5.add(window.kek_solve_current_btn, span=2)
    layout.addLayout(g5.layout())

    # --- Row 5b: Localize (phase 2) + sym_break noise + seed ---
    g5b = GridPlacer(cols=6)
    window.kek_localize_btn = QtWidgets.QPushButton("Localize")
    window.kek_localize_btn.setToolTip("Run localization (phase 2): snap delocalized bond orders to integer (0/1) or aromatic (0.5)")
    window.kek_localize_btn.clicked.connect(lambda: _on_localize(window))
    g5b.add(window.kek_localize_btn, span=1)
    window.kek_symbreak_spin = QtWidgets.QDoubleSpinBox()
    window.kek_symbreak_spin.setRange(0.0, 1.0)
    window.kek_symbreak_spin.setSingleStep(0.01)
    window.kek_symbreak_spin.setValue(0.2)
    window.kek_symbreak_spin.setMaximumWidth(55)
    window.kek_symbreak_spin.setToolTip("Symmetry-breaking noise amplitude added to bond orders before localization")
    g5b.add_pair("Noise:", window.kek_symbreak_spin, label_span=1, input_span=1)
    window.kek_seed_spin = QtWidgets.QSpinBox()
    window.kek_seed_spin.setRange(0, 999999)
    window.kek_seed_spin.setValue(42)
    window.kek_seed_spin.setMaximumWidth(SPIN_MAX_WIDTH)
    g5b.add_pair("Seed:", window.kek_seed_spin, label_span=1, input_span=1)
    window.kek_newseed_btn = QtWidgets.QPushButton("New")
    window.kek_newseed_btn.setToolTip("Generate a random seed")
    window.kek_newseed_btn.clicked.connect(lambda: window.kek_seed_spin.setValue(np.random.randint(1, 999999)))
    g5b.add(window.kek_newseed_btn, span=1)
    layout.addLayout(g5b.layout())

    # --- Status ---
    window.kek_status_label = QtWidgets.QLabel("Status: Ready")
    window.kek_status_label.setWordWrap(True)
    window.kek_status_label.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
    layout.addWidget(window.kek_status_label)

    # --- Bond order display ---
    window.kek_bond_order_label = QtWidgets.QLabel("Bond orders: ---")
    window.kek_bond_order_label.setWordWrap(True)
    layout.addWidget(window.kek_bond_order_label)

    layout.addStretch()

    # View modes: toggle bond order labels
    view_modes = [
        ('Bond Order Labels', lambda: _toggle_bond_order_labels(window)),
    ]

    return UIComponents(panel=panel, edit_modes=[], view_modes=view_modes)


# ---------------------------------------------------------------------------
# Callbacks
# ---------------------------------------------------------------------------

def _get_backend_sys(window):
    """Get AtomicSystem from the window's backend."""
    if hasattr(window, 'backend') and window.backend is not None:
        return window.backend.sys
    return None


def _store_bond_orders_on_window(window, atoms, r):
    """Store solver results on window for rendering in refresh_view."""
    bo_snap = r['bo_snap']
    window.kek_bo_snap = bo_snap
    # Extract pi-active bonds (both atoms have n_pi > 0) and their bond orders
    bonds_all = np.asarray(atoms.bonds, dtype=np.int32)
    n_pi = r['n_pi']
    is_pi = np.asarray(n_pi) > 0
    pi_mask = is_pi[bonds_all[:, 0]] & is_pi[bonds_all[:, 1]] if len(bonds_all) else np.zeros(0, dtype=bool)
    window.bond_order_bonds = bonds_all[pi_mask] if len(pi_mask) else None
    window.bond_orders = bo_snap[pi_mask] if len(pi_mask) else None
    # Store bond orders on graph's Bond objects (total = 1 + pi)
    _store_bond_orders_on_graph(window, atoms, bo_snap, n_pi)


def _store_bond_orders_on_graph(window, atoms, bo_snap, n_pi):
    """Write kekule bond orders onto Bond.order in the AtomicGraph.

    Total bond order = 1 (sigma) + pi_order.  For non-pi bonds (H, sp3) order stays 1.
    Requires window.backend._sync_sys() to have been called so _bond_ids is valid.
    """
    backend = getattr(window, 'backend', None)
    if backend is None or not hasattr(backend, '_bond_ids') or backend._bond_ids is None:
        return
    bonds_all = np.asarray(atoms.bonds, dtype=np.int32) if atoms.bonds is not None else np.zeros((0, 2), dtype=np.int32)
    if len(bonds_all) == 0:
        return
    n_pi = np.asarray(n_pi)
    is_pi = n_pi > 0
    for ib in range(len(bonds_all)):
        bond_id = int(backend._bond_ids[ib])
        bond = backend.graph.bonds.get(bond_id)
        if bond is None:
            continue
        i, j = bonds_all[ib]
        if is_pi[i] and is_pi[j]:
            bond.order = 1.0 + float(bo_snap[ib])
        else:
            bond.order = 1.0


def _on_solve(window):
    """Run the Kekule solver (phase 1 only: delocalized) on the last generated or loaded system."""
    atoms = getattr(window, 'kek_atoms', None)
    if atoms is None:
        # Fallback: use current backend system
        sys = _get_backend_sys(window)
        if sys is None or sys.apos is None or len(sys.apos) == 0:
            window.kek_status_label.setText("Status: No molecule loaded")
            return
        atoms = sys
    try:
        Kval = window.kek_kval_spin.value()
        Kloc = window.kek_kloc_spin.value()
        Karo = window.kek_karo_spin.value()
        allow_aromatic = window.kek_aromatic_chk.isChecked()
        r = run_kekule_solver(atoms, Kval=Kval, Kloc=Kloc, Karo=Karo, allow_aromatic=allow_aromatic, localize=False)
        if r['err'] is not None:
            print(f"[KEKULE] Solve ERROR: {r['err']}")
            tb = r['report'].get('traceback', '')
            if tb: print(tb)
            window.kek_status_label.setText(f"Status: Solve ERROR: {r['err']}")
            return
        window.kek_solver = r['k']  # store solver instance for Localize button
        _store_bond_orders_on_window(window, atoms, r)
        rep = r['report']
        bo_str = np.round(window.bond_orders, 2).tolist() if window.bond_orders is not None else []
        window.kek_bond_order_label.setText(f"Bond orders: {bo_str}")
        window.kek_status_label.setText(
            f"Status: Solved (delocalized) — single={rep['single']} aromatic={rep['aromatic']} double={rep['double']}"
        )
        if hasattr(window, 'refresh_view'):
            window.refresh_view()
    except Exception as e:
        window.kek_status_label.setText(f"Status: Solve FAILED: {e}")
        import traceback; traceback.print_exc()


def _on_solve_current(window):
    """Run the Kekule solver (phase 1 only: delocalized) on the current backend system."""
    sys = _get_backend_sys(window)
    if sys is None or sys.apos is None or len(sys.apos) == 0:
        window.kek_status_label.setText("Status: No molecule loaded")
        return
    try:
        window.backend._sync_sys()  # ensure _bond_ids mapping is valid for graph storage
        sys = window.backend.sys  # re-fetch after sync
        if sys.bonds is None:
            sys.findBonds()
        sys.neighs()
        Kval = window.kek_kval_spin.value()
        Kloc = window.kek_kloc_spin.value()
        Karo = window.kek_karo_spin.value()
        allow_aromatic = window.kek_aromatic_chk.isChecked()
        n_pi = np.asarray(window.backend.atom_npi, dtype=float) if hasattr(window.backend, 'atom_npi') else None
        r = run_kekule_solver(sys, Kval=Kval, Kloc=Kloc, Karo=Karo, allow_aromatic=allow_aromatic, localize=False, n_pi=n_pi)
        if r['err'] is not None:
            print(f"[KEKULE] Solve ERROR: {r['err']}")
            tb = r['report'].get('traceback', '')
            if tb: print(tb)
            window.kek_status_label.setText(f"Status: Solve ERROR: {r['err']}")
            return
        window.kek_solver = r['k']  # store solver instance for Localize button
        _store_bond_orders_on_window(window, sys, r)
        window.kek_atoms = sys  # store for export
        rep = r['report']
        bo_str = np.round(window.bond_orders, 2).tolist() if window.bond_orders is not None else []
        window.kek_bond_order_label.setText(f"Bond orders: {bo_str}")
        window.kek_status_label.setText(
            f"Status: Solved (delocalized) — single={rep['single']} aromatic={rep['aromatic']} double={rep['double']}"
        )
        if hasattr(window, 'refresh_view'):
            window.refresh_view()
    except Exception as e:
        window.kek_status_label.setText(f"Status: Solve FAILED: {e}")
        import traceback; traceback.print_exc()


def _on_localize(window):
    """Run phase 2 (localization) on the stored solver instance from the last Solve."""
    k = getattr(window, 'kek_solver', None)
    if k is None:
        window.kek_status_label.setText("Status: Solve first (delocalized), then Localize")
        return
    atoms = getattr(window, 'kek_atoms', None)
    if atoms is None:
        window.kek_status_label.setText("Status: No molecule to localize")
        return
    try:
        Kloc = window.kek_kloc_spin.value()
        sym_break = window.kek_symbreak_spin.value()
        seed = window.kek_seed_spin.value()
        rep = localize_kekule(k, Kloc=Kloc, sym_break=sym_break, seed=seed)
        bonds_all = np.asarray(atoms.bonds, dtype=np.int32) if atoms.bonds is not None else np.zeros((0, 2), dtype=np.int32)
        n_pi = k.n_pi
        is_pi = n_pi > 0
        pi_mask = is_pi[bonds_all[:, 0]] & is_pi[bonds_all[:, 1]] if len(bonds_all) else np.zeros(0, dtype=bool)
        idx_pi = np.nonzero(pi_mask)[0]
        bo_snap = np.zeros(len(bonds_all), dtype=float)
        bo_snap[idx_pi] = k.pi_bond_orders()
        r = {'bo_snap': bo_snap, 'n_pi': n_pi}
        _store_bond_orders_on_window(window, atoms, r)
        bo_str = np.round(window.bond_orders, 2).tolist() if window.bond_orders is not None else []
        window.kek_bond_order_label.setText(f"Bond orders: {bo_str}")
        if not rep.get('valid', True):
            warn = '; '.join(rep.get('validity', {}).get('issues', []))
            window.kek_status_label.setText(f"Status: Localized (INVALID) — {warn}")
        else:
            window.kek_status_label.setText(
                f"Status: Localized — single={rep['single']} aromatic={rep['aromatic']} double={rep['double']} "
                f"max_err={rep['max_err']:.2e} seed={rep.get('localize_seed', seed)} valid=OK"
            )
        if hasattr(window, 'refresh_view'):
            window.refresh_view()
    except Exception as e:
        window.kek_status_label.setText(f"Status: Localize FAILED: {e}")
        import traceback; traceback.print_exc()


def _toggle_bond_order_labels(window):
    """Toggle bond order label display in the scene."""
    window.show_bond_order_labels = not window.show_bond_order_labels
    if hasattr(window, 'refresh_view'):
        window.refresh_view()
