#!/usr/bin/env python3
"""Compute electron density (rho_scf) for all z-scan molecules and methods.

Saves both .npy (for fast programmatic access) and .cub (for visualization in VESTA/Avogadro).
Uses the same MOLECULES and METHODS definitions as run_zscan_reference.py.

Grid: step=0.1 Å, margin=5.0 Å, z_extra=6.0 Å — fine grid for accurate Pauli convolution.
Each molecule gets one density per method. Densities are saved to debug/densities/.

Usage:
  python tests/SPM/compute_densities.py
  python tests/SPM/compute_densities.py --molecules H2O --methods dftb_3ob
"""
import os, sys, argparse, time
import numpy as np

_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.realpath(os.path.join(_THIS_DIR, '..', '..'))
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

from tests.SPM.run_zscan_reference import MOLECULES, METHODS, load_molecule

DENS_DIR = os.path.join(_ROOT, 'debug', 'densities')

ELEM_Z = {'H': 1, 'C': 6, 'N': 7, 'O': 8, 'P': 15, 'S': 16}


def write_cube(filename, density, origin, step, atom_names, atom_pos, title="rho_scf"):
    """Write Gaussian cube file for a 3D scalar field."""
    nx, ny, nz = density.shape
    natoms = len(atom_names)
    with open(filename, 'w') as f:
        f.write(f"{title}\n")
        f.write("Generated by compute_densities.py\n")
        f.write(f"{natoms:5d} {origin[0]:12.6f} {origin[1]:12.6f} {origin[2]:12.6f}\n")
        f.write(f"{nx:5d} {step:12.6f} {0.0:12.6f} {0.0:12.6f}\n")
        f.write(f"{ny:5d} {0.0:12.6f} {step:12.6f} {0.0:12.6f}\n")
        f.write(f"{nz:5d} {0.0:12.6f} {0.0:12.6f} {step:12.6f}\n")
        for name, pos in zip(atom_names, atom_pos):
            Z = ELEM_Z.get(name, 6)
            f.write(f"{Z:5d} {float(Z):12.6f} {pos[0]:12.6f} {pos[1]:12.6f} {pos[2]:12.6f}\n")
        flat = density.T.flatten()  # cube expects z-fastest
        for i, val in enumerate(flat):
            if i % 6 == 0: f.write("\n")
            f.write(f"{val:13.5E}")
        f.write("\n")


def compute_density_dftb(atom_pos, atom_names, basis_name, step, margin, z_extra, work_dir):
    """Compute rho_scf using DFTBcore dense projection via AFM_utils.get_density_from_dftb_dense."""
    from spammm.SPM import AFM_utils as afm_utils
    from spammm.quantum.DFTB_utils import WFC_HSD_PATHS
    atom_types = np.array([ELEM_Z.get(n, 6) for n in atom_names], dtype=np.int32)
    basis_hsd = WFC_HSD_PATHS[basis_name]
    result = afm_utils.get_density_from_dftb_dense(
        atom_pos, atom_types, basis_hsd, work_dir,
        step=step, margin=margin, z_extra=z_extra, verbosity=0)
    return result


def compute_density_pyscf(atom_pos, atom_names, basis, xc, step, margin, z_extra):
    """Compute rho_scf using pySCF via AFM_utils.get_density_from_pyscf.
    Converts density from e/Bohr³ (pySCF internal) to e/Å³ for grid consistency."""
    from spammm.SPM import AFM_utils as afm_utils
    BOHR_PER_ANG = 1.8897259886
    atom_types = np.array([ELEM_Z.get(n, 6) for n in atom_names], dtype=np.int32)
    method = 'RKS' if xc else 'RHF'
    result = afm_utils.get_density_from_pyscf(
        atom_pos, atom_types, step=step, margin=margin, z_extra=z_extra,
        basis=basis, method=method, xc=xc, verbosity=0)
    # pySCF eval_rho returns density in e/Bohr³, convert to e/Å³
    result['rho_scf'] = result['rho_scf'] * (BOHR_PER_ANG ** 3)
    result['rho_na'] = result['rho_na'] * (BOHR_PER_ANG ** 3)
    result['rho_diff'] = result['rho_diff'] * (BOHR_PER_ANG ** 3)
    return result


def main():
    parser = argparse.ArgumentParser(description='Compute electron densities for z-scan molecules')
    parser.add_argument('--molecules', type=str, default='all', help='Comma-separated molecule names')
    parser.add_argument('--methods', type=str, default='all', help='Comma-separated method names')
    parser.add_argument('--step', type=float, default=0.1, help='Grid step [Ang]')
    parser.add_argument('--margin', type=float, default=5.0, help='Grid margin [Ang]')
    parser.add_argument('--z_extra', type=float, default=6.0, help='Extra z margin [Ang]')
    parser.add_argument('--outdir', default=DENS_DIR, help='Output directory')
    args = parser.parse_args()

    outdir = os.path.join(_ROOT, args.outdir) if not os.path.isabs(args.outdir) else args.outdir
    os.makedirs(outdir, exist_ok=True)

    mol_names = list(MOLECULES.keys()) if args.molecules == 'all' else args.molecules.split(',')
    method_names = list(METHODS.keys()) if args.methods == 'all' else args.methods.split(',')

    step, margin, z_extra = args.step, args.margin, args.z_extra

    for mol_name in mol_names:
        if mol_name not in MOLECULES:
            print(f"WARNING: Unknown molecule {mol_name}, skipping")
            continue
        mol_info = MOLECULES[mol_name]
        atom_pos, atom_names = load_molecule(mol_info['xyz'])
        print(f"\n{'='*60}")
        print(f"Molecule: {mol_name} ({len(atom_names)} atoms)")
        print(f"{'='*60}")

        # Use per-molecule method list
        mol_methods = mol_info.get('methods', list(METHODS.keys()))
        mol_methods = [m for m in mol_methods if m in method_names]

        for method_name in mol_methods:
            if method_name not in METHODS:
                print(f"  WARNING: Unknown method {method_name}, skipping")
                continue

            # Check cache
            npy_path = os.path.join(outdir, f'rho_{mol_name}_{method_name}.npy')
            cub_path = os.path.join(outdir, f'rho_{mol_name}_{method_name}.cub')
            meta_path = os.path.join(outdir, f'rho_{mol_name}_{method_name}.meta.npz')
            if os.path.exists(npy_path) and os.path.exists(meta_path):
                print(f"  [CACHE] {mol_name}/{method_name}: already computed, skipping")
                continue

            method = METHODS[method_name]
            t0 = time.time()
            print(f"  [{method_name}] Computing density...")

            try:
                if method['type'] == 'dftb':
                    work_dir = os.path.join(outdir, 'work', f'{mol_name}_{method_name}')
                    result = compute_density_dftb(
                        atom_pos, atom_names, method['basis'],
                        step, margin, z_extra, work_dir)
                elif method['type'] == 'pyscf':
                    result = compute_density_pyscf(
                        atom_pos, atom_names, method['basis'], method.get('xc'),
                        step, margin, z_extra)
                else:
                    print(f"  ERROR: Unknown method type {method['type']}")
                    continue
            except Exception as exc:
                print(f"  ERROR: {exc}")
                continue

            rho_scf = result['rho_scf']
            origin = result['origin']
            ngrid = result['ngrid']

            # Save .npy (raw density array)
            np.save(npy_path, rho_scf)
            print(f"  Saved: {npy_path}  shape={rho_scf.shape}")

            # Save metadata (origin, ngrid, step, atom info)
            np.savez(meta_path,
                     origin=origin, ngrid=ngrid, step=step,
                     atom_pos=atom_pos, atom_names=np.array(atom_names))
            print(f"  Saved: {meta_path}")

            # Save .cub (for visualization)
            write_cube(cub_path, rho_scf, origin, step, atom_names, atom_pos,
                       title=f"rho_scf {mol_name} {method_name}")
            print(f"  Saved: {cub_path}")

            # Charge check
            q = rho_scf.sum() * step**3
            n_elec_expected = sum(ELEM_Z.get(n, 6) for n in atom_names)
            print(f"  Charge check: q={q:.3f} (expected ~{n_elec_expected})")
            print(f"  Time: {time.time()-t0:.1f}s")

    print(f"\nAll densities saved to {outdir}/")


if __name__ == '__main__':
    main()
