#!/usr/bin/env python3
"""Standalone script: project electron density from DFTB+ and save visual outputs.

Generates:
  1. PNG with 2D imshow slices of rho_scf, rho_na, rho_diff at several z-heights
  2. Gaussian .cub file for rho_scf (loadable in VESTA, Avogadro, etc.)

Usage:
  python tests/SPM/plot_density_projection.py [--basis 3ob-3-1] [--xyz data/xyz/H2O.xyz]
"""
import os, sys, argparse, numpy as np

os.environ.setdefault('PYOPENCL_CTX', '0')
os.environ.setdefault('PYOPENCL_COMPILER_OUTPUT', '1')

def write_cube(filename, density, origin, step, atom_names, atom_pos):
    """Write a Gaussian cube file for a 3D scalar field."""
    nx, ny, nz = density.shape
    natoms = len(atom_names)
    with open(filename, 'w') as f:
        f.write("Electron density from DFTB+ projection (rho_scf)\n")
        f.write("Generated by plot_density_projection.py\n")
        f.write(f"{natoms:5d} {origin[0]:12.6f} {origin[1]:12.6f} {origin[2]:12.6f}\n")
        f.write(f"{nx:5d} {step:12.6f} {0.0:12.6f} {0.0:12.6f}\n")
        f.write(f"{ny:5d} {0.0:12.6f} {step:12.6f} {0.0:12.6f}\n")
        f.write(f"{nz:5d} {0.0:12.6f} {0.0:12.6f} {step:12.6f}\n")
        Z_map = {'H':1,'C':6,'N':7,'O':8,'F':9,'Si':14,'P':15,'S':16,'Cl':17,'Na':11,'Mg':12,'K':19,'Ca':20}
        for i, (name, pos) in enumerate(zip(atom_names, atom_pos)):
            Z = Z_map.get(name, 6)
            f.write(f"{Z:5d} {float(Z):12.6f} {pos[0]:12.6f} {pos[1]:12.6f} {pos[2]:12.6f}\n")
        flat = density.T.flatten()  # cube expects (x,y,z) with z fastest
        for i, val in enumerate(flat):
            if i % 6 == 0: f.write("\n")
            f.write(f"{val:13.5E}")
        f.write("\n")

def main():
    parser = argparse.ArgumentParser(description="Project DFTB density and save PNG + CUB")
    parser.add_argument('--xyz', default='data/xyz/H2O.xyz', help='XYZ file path')
    parser.add_argument('--basis', default='3ob-3-1', help='DFTB basis set')
    parser.add_argument('--step', type=float, default=0.15, help='Grid step [Ang]')
    parser.add_argument('--margin', type=float, default=4.0, help='Grid margin [Ang]')
    parser.add_argument('--outdir', default='debug/plot_density_projection', help='Output directory')
    args = parser.parse_args()

    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt

    from spammm.SPM import AFM as afm
    from spammm.SPM import AFM_utils as afm_utils
    from spammm.config_utils import get_dftb_basis_path
    import spammm.atomicUtils as au

    os.makedirs(args.outdir, exist_ok=True)

    # Load molecule
    pos, _, names, _, _ = au.load_xyz(args.xyz)
    ELEM_Z = {'H':1,'C':6,'N':7,'O':8,'F':9,'Si':14,'P':15,'S':16,'Cl':17,'Na':11,'Mg':12,'K':19,'Ca':20}
    atomPos = np.array(pos, dtype=np.float64)
    enames = list(names)
    atomTypes = np.array([ELEM_Z.get(e, 6) for e in enames], dtype=np.int32)
    print(f"Molecule: {enames}  ({len(enames)} atoms)")
    print(f"Positions:\n{atomPos}")

    # Setup grid
    grid_spec, origin, ngrid = afm.setup_density_grid(atomPos, step=args.step, margin=args.margin, z_extra=6.0)
    print(f"Grid: {ngrid}  step={args.step}  origin={origin}")

    # Run DFTB+ SCF + density projection
    basis_hsd_path = get_dftb_basis_path(args.basis)
    print(f"Basis HSD: {basis_hsd_path}")
    work_dir = os.path.join(args.outdir, 'dftb_work')
    os.makedirs(work_dir, exist_ok=True)

    result = afm_utils.get_density_from_dftb_dense(
        atomPos, atomTypes, basis_hsd_path, work_dir,
        grid_spec=grid_spec, step=args.step, margin=args.margin, z_extra=6.0,
        verbosity=1
    )

    rho_scf = result['rho_scf']
    rho_na  = result['rho_na']
    rho_diff = result['rho_diff']
    V_ES    = result['V_ES']

    dV = args.step**3
    n_e_scf = rho_scf.sum() * dV
    n_e_na  = rho_na.sum() * dV
    q_diff  = rho_diff.sum() * dV
    print(f"\n=== Density Summary ===")
    print(f"rho_scf: shape={rho_scf.shape}, range=[{rho_scf.min():.4e}, {rho_scf.max():.4e}]")
    print(f"rho_na:  range=[{rho_na.min():.4e}, {rho_na.max():.4e}]")
    print(f"rho_diff: range=[{rho_diff.min():.4e}, {rho_diff.max():.4e}]")
    print(f"N_e SCF={n_e_scf:.3f}, N_e NA={n_e_na:.3f}, q_diff={q_diff:.4f}")
    print(f"V_ES: range=[{V_ES.min():.4e}, {V_ES.max():.4e}]")

    # === Save .cub file ===
    cub_path = os.path.join(args.outdir, f'rho_scf_{os.path.basename(args.xyz).replace(".xyz","")}.cub')
    write_cube(cub_path, rho_scf, origin, args.step, enames, atomPos)
    print(f"\nSaved cube file: {cub_path}")

    # === Save PNG with 2D slices ===
    mol_z = float(atomPos[:,2].max())
    mol_x = [float(atomPos[:,0].min()), float(atomPos[:,0].max())]
    mol_y = [float(atomPos[:,1].min()), float(atomPos[:,1].max())]
    extent_xy = [float(origin[0]), float(origin[0] + ngrid[0]*args.step),
                 float(origin[1]), float(origin[1] + ngrid[1]*args.step)]

    # Select z-slices: through molecule, above, and below
    z_vals = [mol_z - 0.5, mol_z, mol_z + 0.5, mol_z + 1.5, mol_z + 3.0]
    sel_iz = []
    z_labels = []
    for zv in z_vals:
        iz = int((zv - origin[2]) / args.step)
        if 0 <= iz < ngrid[2]:
            sel_iz.append(iz)
            z_labels.append(f'z={zv:.1f}Å')

    components = [
        ('rho_scf',  rho_scf,  'hot'),
        ('rho_na',   rho_na,   'hot'),
        ('rho_diff', rho_diff, 'bwr'),
        ('V_ES',     V_ES,     'bwr'),
    ]

    fig, axes = plt.subplots(len(components), len(sel_iz), figsize=(3*len(sel_iz), 2.5*len(components)))
    for row, (label, field, cmap) in enumerate(components):
        for col, iz in enumerate(sel_iz):
            ax = axes[row, col]
            data = field[:,:,iz].T
            if cmap == 'bwr':
                vabs = max(float(np.percentile(np.abs(data), 99)), 1e-30)
                im = ax.imshow(data, origin='lower', cmap=cmap, aspect='equal', vmin=-vabs, vmax=vabs, extent=extent_xy)
            else:
                vmax = max(float(np.percentile(data, 99)), 1e-30)
                im = ax.imshow(data, origin='lower', cmap=cmap, aspect='equal', vmin=0, vmax=vmax, extent=extent_xy)
            ax.set_title(z_labels[col], fontsize=7)
            ax.tick_params(labelsize=5)
            if col == 0: ax.set_ylabel(label, fontsize=7)
            if row == len(components)-1: ax.set_xlabel('x (Å)', fontsize=7)
            # Mark atom positions
            for i, (x, y, z) in enumerate(atomPos):
                if abs(z - (origin[2] + iz*args.step)) < args.step:
                    ax.plot(x, y, 'w+', markersize=8, markeredgewidth=1.5)
            plt.colorbar(im, ax=ax, shrink=0.7)
    fig.suptitle(f'DFTB Density Projection — {os.path.basename(args.xyz)} (basis={args.basis})', fontsize=12)
    fig.tight_layout()
    png_path = os.path.join(args.outdir, f'density_slices_{os.path.basename(args.xyz).replace(".xyz","")}.png')
    fig.savefig(png_path, dpi=150)
    plt.close(fig)
    print(f"Saved PNG: {png_path}")

    # === Also save a yz cross-section (through the molecule center) ===
    ix_center = int((float(atomPos[:,0].mean()) - origin[0]) / args.step)
    z_range = [float(origin[2]), float(origin[2] + ngrid[2]*args.step)]
    y_range = [float(origin[1]), float(origin[1] + ngrid[1]*args.step)]
    extent_yz = [y_range[0], y_range[1], z_range[0], z_range[1]]

    fig2, axes2 = plt.subplots(1, 3, figsize=(12, 4))
    for col, (label, field, cmap) in enumerate([('rho_scf', rho_scf, 'hot'), ('rho_diff', rho_diff, 'bwr'), ('V_ES', V_ES, 'bwr')]):
        ax = axes2[col]
        data = field[ix_center,:,:].T  # (ny, nz) -> transpose for (z, y)
        if cmap == 'bwr':
            vabs = max(float(np.percentile(np.abs(data), 99)), 1e-30)
            im = ax.imshow(data, origin='lower', cmap=cmap, aspect='equal', vmin=-vabs, vmax=vabs, extent=extent_yz)
        else:
            vmax = max(float(np.percentile(data, 99)), 1e-30)
            im = ax.imshow(data, origin='lower', cmap=cmap, aspect='equal', vmin=0, vmax=vmax, extent=extent_yz)
        ax.set_title(f'{label} (x={origin[0]+ix_center*args.step:.2f}Å)', fontsize=9)
        ax.set_xlabel('y (Å)', fontsize=8)
        if col == 0: ax.set_ylabel('z (Å)', fontsize=8)
        # Mark atom positions
        for i, (x, y, z) in enumerate(atomPos):
            if abs(x - (origin[0] + ix_center*args.step)) < args.step:
                ax.plot(y, z, 'w+', markersize=8, markeredgewidth=1.5)
        plt.colorbar(im, ax=ax, shrink=0.7)
    fig2.suptitle(f'DFTB Density YZ cross-section — {os.path.basename(args.xyz)}', fontsize=12)
    fig2.tight_layout()
    png_yz = os.path.join(args.outdir, f'density_yz_{os.path.basename(args.xyz).replace(".xyz","")}.png')
    fig2.savefig(png_yz, dpi=150)
    plt.close(fig2)
    print(f"Saved YZ cross-section: {png_yz}")

    print(f"\nDone! Check the {args.outdir}/ directory for outputs.")

if __name__ == '__main__':
    main()
